apiVersion: v1
kind: Pod
metadata: 
  name: sonarqube-pod
  labels: 
    app: sonarqube-app
spec:
  containers: 
  - name: sonarqube
    image: sonarqube:latest
---
apiVersion: v1
kind: Service
metadata: 
  name: sonarqube-service
spec: 
  type: ClusterIP
  ports:
  - name: http
    targetPort: 900
    port: 9004
  selector: 
    app: sonarqube-app
