apiVersion: v1
kind: Pod
metadata: 
  name: myapp-pod
  labels: 
    app: myapp
spec: 
  containers: 
  - name: tuxotron
    image: tuxotron/xvwa
---
apiVersion: v1
kind: Service
metadata: 
  name: myapp-service

spec: 
  type: ClusterIP
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector: 
    app: myapp
